name: Manager
on:
  pull_request:
    paths:
      - '.github/workflows/manager.yml'
  schedule:
    - cron: '22 02 * * *'
  workflow_dispatch:
jobs:
  manager:
    runs-on: ubuntu-slim
    steps:
      - run: /usr/bin/true
