name: OpenIndiana
on:
  pull_request:
    paths:
      - '.github/actions/**'
      - '.github/workflows/openindiana.yml'
  schedule:
    - cron: '22 02 * * *'
  workflow_dispatch:
    inputs:
      skip_functional_tests:
        description: 'Skip functional tests'
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  CCACHE_COMPILERCHECK: content
  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_MAXSIZE: 600M
  CCACHE_COMPRESS: 1
  # See: https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories.
  CI_NCPU: 4

jobs:
  openindiana:
    name: 'OpenIndiana: system libs, no GUI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: openindiana {0}

    steps:
      - name: Checkout Bitcoin Core repo
        uses: actions/checkout@v6
        with:
          repository: bitcoin/bitcoin

      - name: Start OpenIndiana VM
        uses: vmactions/openindiana-vm@v0
        with:
          envs: 'CCACHE_COMPILERCHECK CCACHE_DIR CCACHE_MAXSIZE CCACHE_COMPRESS'
          # The `pkg install` command often encounters networking issues in the CI
          # environment. To mitigate these, the following steps have been taken:
          # 1. Each package is installed individually.
          # 2. `library/libevent2` and `database/sqlite-3` are already preinstalled
          #    on the VM image, so they are skipped.
          # 3. Installing `system/library/boost` is skipped, as it often takes
          #    more than 60 minutes and causes a job timeout.
          #    See the "Build Boost" step below.
          prepare: |
            set -e
            pkg list > packages_before
            pkg install developer/versioning/git
            pkg install developer/build/cmake
            pkg install developer/build/pkgconf
            pkg install developer/gcc-14
            pkg install developer/ccache
            pkg install library/c++/zeromq
            pkg install runtime/python-314
            pkg list > packages_after
            diff -w packages_before packages_after | grep '^>' || true
          run: git config --global --add safe.directory ${{ github.workspace }}
          sync: 'rsync'
          copyback: false

      - name: Build Boost
        run: |
          set -e
          wget --progress=dot:mega https://github.com/boostorg/boost/releases/download/boost-1.90.0/boost-1.90.0-cmake.tar.xz
          tar xf boost-1.90.0-cmake.tar.xz
          cmake -S boost-1.90.0 -B build-boost \
            -DBOOST_INCLUDE_LIBRARIES="multi_index;signals2;test" \
            -DBOOST_TEST_HEADERS_ONLY=ON \
            -DBOOST_ENABLE_MPI=OFF \
            -DBOOST_ENABLE_PYTHON=OFF \
            -DBOOST_INSTALL_LAYOUT=system \
            -DBUILD_TESTING=OFF \
            -DCMAKE_DISABLE_FIND_PACKAGE_ICU=ON
          cmake --build build-boost
          cmake --install build-boost

      - name: Checkout helper actions
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/actions
          path: ci/nightly

      - name: Generate buildsystem
        run: |
          cd ${{ github.workspace }}
          # Workaround for a bug in the FindThreads module.
          # See: https://gitlab.kitware.com/cmake/cmake/-/issues/26063
          export CXXFLAGS="-pthread"
          cmake -B build --preset dev-mode \
            -DBUILD_GUI=OFF \
            -DBUILD_SHARED_LIBS=OFF \
            `# TODO: Build Cap'n Proto from source and reenable IPC.` \
            -DENABLE_IPC=OFF \
            -DWITH_USDT=OFF \
            -DWERROR=ON

      - name: Build
        uses: ./ci/nightly/.github/actions/build-with-ccache
        with:
          vm: openindiana

      - name: Check 'bitcoind' executable
        run: |
          set -e
          cd ${{ github.workspace }}
          ls -l build/bin/bitcoind
          file build/bin/bitcoind
          ldd build/bin/bitcoind
          ./build/bin/bitcoind -version

      - name: Run test suite
        uses: ./ci/nightly/.github/actions/run-test-suite
        with:
          vm: openindiana
          # TODO: Fix the code, then enable system_tests.
          options: '--exclude-regex "^system_tests$"'

      - name: Run functional tests
        if: ${{ ! inputs.skip_functional_tests }}
        # TODO: Fix the excluded tests and re-enable them.
        # See: https://github.com/bitcoin/bitcoin/issues/33128.
        FUNCTIONAL_TESTS_EXCLUDE: '--exclude feature_reindex_init.py,feature_rbf.py,feature_reindex_init.py,feature_settings.py,interface_bitcoin_cli.py,mempool_persist.py,mempool_unbroadcast.py,rpc_psbt.py,tool_wallet.py,wallet_abandonconflict.py,wallet_address_types.py,wallet_anchor.py,wallet_assumeutxo.py,wallet_avoidreuse.py,wallet_backup.py,wallet_balance.py,wallet_basic.py,wallet_blank.py,wallet_bumpfee.py,wallet_conflicts.py,wallet_create_tx.py,wallet_createwallet.py,wallet_descriptor.py,wallet_encryption.py,wallet_fallbackfee.py,wallet_fast_rescan.py,wallet_fundrawtransaction.py,wallet_gethdkeys.py,wallet_hd.py,wallet_importdescriptors.py,wallet_keypool.py,wallet_keypool_topup.py,wallet_listdescriptors.py,wallet_listreceivedby.py,wallet_listsinceblock.py,wallet_listtransactions.py,wallet_miniscript.py,wallet_multiwallet.py,wallet_musig.py,wallet_reindex.py,wallet_reorgsrestore.py,wallet_rescan_unconfirmed.py,wallet_resendwallettransactions.py,wallet_send.py,wallet_signer.py,wallet_signrawtransactionwithwallet.py,wallet_simulaterawtx.py,wallet_spend_unconfirmed.py,wallet_startup.py,wallet_taproot.py,wallet_timelock.py,wallet_transactiontime_rescan.py,wallet_txn_clone.py,wallet_txn_doublespend.py,wallet_v3_txs.py'
        run: |
          cd ${{ github.workspace }}
          python3.14 -m ensurepip
          python3.14 -m pip install setuptools wheel
          python3.14 -m pip install pycapnp
          python3.14 -m pip install pyzmq
          python3.14 ./build/test/functional/test_runner.py --ci --extended -j $((${{ env.CI_NCPU }} * 2)) --combinedlogslen=99999999 --tmpdirprefix . --timeout-factor=8 ${{ env.FUNCTIONAL_TESTS_EXCLUDE }}
